services:
  db:
    hostname: mongo_server
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .mongo.env
    networks:
      - engine_network

  engine:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - engine_network

networks:
  engine_network:
    driver: bridge
