version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: logs/api/debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
loggers:
  uvicorn:
    level: INFO
    handlers: [console, debug_file_handler]
    propagate: false
root:
  level: INFO
  handlers: [console, debug_file_handler]
