[tool.poetry]
name = "news_extractor_engine"
version = "1.0.0"
authors = ["Avin Divakara <divakaraavin@gmail.com>"]
description = "A Python package for extracting news from various sources."


[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.2.2"
bs4 = "^0.0.2"
aiohttp = "^3.9.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"